version: '3.1'

services:

  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      MYSQL_DATABASE: prepaid

  adminer:
      image: adminer
      restart: always
      ports:
        - 9090:8080

  money-transfer:
    image: revolut/money-transfer:1.0.0-SNAPSHOT
    container_name: money-transfer
    depends_on:
      - postgres
    ports:
      - 8081:8080
      - 50505:50505
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: mysql
      DATABASE_PORT: 3307
      DATABASE_NAME: prepaid
      MAX_CONNECTION_POOL_SIZE: 10
      MAX_REQUEST_THREADS_POOL_SIZE: 200




